[build]
  command = "npm run build"
  publish = ".next"

[functions]
  external_node_modules = ["@netlify/functions"]
  
[[plugins]]
  package = "@netlify/plugin-nextjs"
  # Use a specific version known to work
  [plugins.inputs]
    tscOptions = '{"noEmit": true}'

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_FORCE_EDGE_IMAGES = "true"
  # Enable Next.js cache
  NEXT_PUBLIC_NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_DISABLE_METADATA_ROUTE_NAMESPACE = "true"

# Cache Next.js build folders 
[[plugins]]
  package = "netlify-plugin-cache-nextjs"

# This section prevents Netlify Forms preprocessing in Next.js
[build.processing.html]
  pretty_urls = false

# Forms processing rules
[build.processing.forms]
  ignore = [".next/**/*", "node_modules/**/*"]

# Redirect rule for successful form submissions
[[redirects]]
  from = "/thank-you"
  to = "/thank-you"
  status = 200

[[redirects]]
  from = "/thank-you-under-21"
  to = "/thank-you-under-21"
  status = 200 